import type { NextPage } from "next";
import Head from "next/head";
import { GetStaticProps } from "next";

// ページコンポーネントに渡されるデータ
type Props = {
  channel_data: any;
};

// この関数がビルド時に呼び出され、戻り値の props の値がページコンポーネントに渡される
export const getStaticProps: GetStaticProps<Props> = async (context) => {
  const channelID = "UCXBgKqFxSjKADEuMLkc1Bpg";

  const res = await fetch(
    "https://www.googleapis.com/youtube/v3/channels?part=" +
      "snippet" +
      "&id=" +
      channelID +
      "&key=" +
      process.env.YOUTUBE_API_KEY
  );
  const data = await res.json();

  const res2 = await fetch(
    "https://www.googleapis.com/youtube/v3/channels?part=" +
      "brandingSettings" +
      "&id=" +
      channelID +
      "&key=" +
      process.env.YOUTUBE_API_KEY
  );
  const data2 = await res2.json();

  const res3 = await fetch(
    "https://www.googleapis.com/youtube/v3/channels?part=" +
      "statistics" +
      "&id=" +
      channelID +
      "&key=" +
      process.env.YOUTUBE_API_KEY
  );
  const data3 = await res3.json();

  if (!data || !data2 || !data3) {
    return {
      notFound: true,
    };
  }
  const channel_data = [data, data2, data3];

  return {
    props: { channel_data }, // will be passed to the page component as props
  };
};

const Index: React.FC<Props> = ({ channel_data }) => {
  const snippet_data = channel_data[0].items[0].snippet;
  const brandingSettings_data = channel_data[1].items[0].brandingSettings;
  const statics_data = channel_data[2].items[0].statistics;

  return (
    <div>
      <Head>
        <title>Gama Trophy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-2">
        <p className="text-4xl my-2">Snippet</p>

        {channel_data[0].items && (
          <ul>
            <li>Title：{snippet_data.title}</li>
            <li>cunstomUrl：{snippet_data.customUrl}</li>
            <li>Description：{snippet_data.description}</li>
            <li>
              Thumbnails：
              <img
                src={snippet_data.thumbnails.default.url}
                alt={snippet_data.title}
              />
            </li>
          </ul>
        )}

        <p className="text-4xl my-2">brandingSettings</p>

        {channel_data[1].items && (
          <div>
            bannerExternalUrl：
            <img
              src={brandingSettings_data.image.bannerExternalUrl}
              alt={brandingSettings_data.channel.title + "Banner"}
            />
          </div>
        )}

        <p className="text-4xl my-2">statistics</p>

        {channel_data[2].items && (
          <ul>
            <li>
              再生回数：
              {statics_data.viewCount}
            </li>
            <li>
              登録者数：
              {statics_data.subscriberCount}
            </li>
            <li>
              アップロードされた動画の数：
              {statics_data.videoCount}
            </li>
          </ul>
        )}
      </main>

      <footer></footer>
    </div>
  );
};

export default Index;
