import Head from "next/head";
import { GetStaticProps } from "next";
import Link from "next/link";

// ページコンポーネントに渡されるデータ
type Props = {
  streamers: { name: string; channelID: string; bannerURL: string }[];
};

// この関数がビルド時に呼び出され、戻り値の props の値がページコンポーネントに渡される
export const getStaticProps: GetStaticProps<Props> = async (context) => {
  const streamers = await require("../data/streamer.json");

  if (!streamers) {
    return {
      notFound: true,
    };
  }

  for (const [index, streamer] of streamers.entries()) {
    const res = await fetch(
      "https://www.googleapis.com/youtube/v3/channels?part=" +
        "snippet" +
        "&id=" +
        streamers[index].channelID +
        "&key=" +
        process.env.YOUTUBE_API_KEY
    );
    const data = await res.json();

    if (!data) {
      return {
        notFound: true,
      };
    }
    streamers[index].bannerURL = data.items[0].snippet.thumbnails.default.url;
  }

  return {
    props: { streamers }, // will be passed to the page component as props
  };
};

// 文字数制限
const check = (text: string) => {
  if (text.length >= 7) {
    return text.slice(0, 7) + "…";
  } else {
    return text;
  }
};

const List: React.FC<Props> = ({ streamers }) => {
  console.log(streamers);

  return (
    <div className="">
      <Head>
        <title>Gama Trophy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-2">
        <p className="text-4xl text-center my-3 text-blue-400">Streamer一覧</p>
        <div className="grid grid-flow-row grid-cols-2 gap-2">
          {streamers &&
            streamers.map(
              (
                streamer: {
                  name: string;
                  channelID: string;
                  bannerURL: string;
                },
                index
              ) => {
                return (
                  <Link
                    href={"/streamers/" + index}
                    passHref
                    key={streamer.name + "_card"}
                  >
                    <div className="cursor-pointer relative">
                      <img
                        src={streamer.bannerURL}
                        alt={streamer.name}
                        className="opacity-75 object-cover w-full h-20"
                      />
                      <p className="whitespace-nowrap font-serif text-white absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-base p-2 opacity-100border-solid border-2">
                        {check(streamer.name)}
                      </p>
                    </div>
                  </Link>
                );
              }
            )}
        </div>
      </main>

      <footer></footer>
    </div>
  );
};

export default List;
